---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_remote_tmp: /tmp/.ansible-remote/tmp
        # 실제 키가 아니라 Molecule 테스트 전용 더미 값
        munge_key_b64: "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQQ=="
verifier:
  name: ansible
