---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_remote_tmp: /tmp/.ansible-remote/tmp
        # munge_key_b64는 converge.yml에서 테스트용으로 그때그때 만든다.
verifier:
  name: ansible
