---
- name: Ensure mariadb-server is installed
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: true

- name: Ensure mariadb is enabled and running
  ansible.builtin.systemd_service:
    name: mariadb
    enabled: true
    state: started

- name: Check whether slurm accounting database exists
  ansible.builtin.command: >-
    mysql --batch --skip-column-names -e
    "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA
    WHERE SCHEMA_NAME='slurm_acct_db'"
  register: mariadb_db_check
  changed_when: false

- name: Create slurm accounting database
  ansible.builtin.command: mysql -e "CREATE DATABASE slurm_acct_db"
  when: "'slurm_acct_db' not in mariadb_db_check.stdout"

- name: Check whether slurm DB user exists
  ansible.builtin.command: >-
    mysql --batch --skip-column-names -e
    "SELECT User FROM mysql.user WHERE User='slurm' AND Host='localhost'"
  register: mariadb_user_check
  changed_when: false

- name: Create slurm DB user and grant privileges
  ansible.builtin.command: >-
    mysql -e "CREATE USER 'slurm'@'localhost'
    IDENTIFIED BY '{{ slurmdbd_db_password }}';
    GRANT ALL PRIVILEGES ON slurm_acct_db.* TO 'slurm'@'localhost';
    FLUSH PRIVILEGES;"
  when: "'slurm' not in mariadb_user_check.stdout"
  no_log: true
