---
- name: Restart slurmdbd
  ansible.builtin.systemd_service:
    name: slurmdbd
    state: restarted

- name: Restart slurmctld
  ansible.builtin.systemd_service:
    name: slurmctld
    state: restarted
