---
- name: Restart Prometheus
  ansible.builtin.command: docker restart prometheus
  changed_when: true

- name: Restart Alertmanager
  ansible.builtin.command: docker restart alertmanager
  changed_when: true
