---
- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: true

- name: Ensure chrony is enabled and running
  ansible.builtin.service:
    name: chrony
    enabled: true
    state: started
