---
- name: Configure head as gateway
  ansible.builtin.include_tasks: head.yml
  when: "'headnode' in group_names"

- name: Configure workers to route via head
  ansible.builtin.include_tasks: worker.yml
  when: "'workers' in group_names"
