---
- name: Ensure prometheus-alertmanager is installed
  ansible.builtin.apt:
    name: prometheus-alertmanager
    state: present
    update_cache: true

- name: Deploy alertmanager.yml
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    owner: root
    group: root
    mode: '0644'
    validate: /usr/bin/amtool check-config %s
  notify: Restart alertmanager

- name: Ensure prometheus-alertmanager is enabled and running
  ansible.builtin.systemd_service:
    name: prometheus-alertmanager
    enabled: true
    state: started
