---
- name: Ensure munge is installed
  ansible.builtin.apt:
    name: munge
    state: present
    update_cache: true

- name: Deploy shared munge key
  ansible.builtin.copy:
    content: "{{ munge_key_b64 | b64decode }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: '0400'
  notify: Restart munged

- name: Ensure munged is enabled and running
  ansible.builtin.service:
    name: munge
    enabled: true
    state: started
