---
- name: Configure all cluster nodes
  hosts: cluster
  become: true
  roles:
    - common
    - munge
    - slurm-common

- name: Configure head node services
  hosts: headnode
  become: true
  roles:
    - mariadb
    - nfs-server
    - slurm-ctld

- name: Configure worker nodes
  hosts: workers
  become: true
  roles:
    - nfs-client
    - slurm-d
