---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
provisioner:
  name: ansible
  inventory:
    hosts:
      cluster:
        hosts:
          instance: {}
    group_vars:
      all:
        ansible_remote_tmp: /tmp/.ansible-remote/tmp
        common_shared_user: hpcuser
        common_shared_uid: 2000
        common_shared_gid: 2000
        common_ssh_password_authentication: false
verifier:
  name: ansible
